### PR TITLE
Date format validation

### PR DESCRIPTION
**Pull request by adrai**
I can't validate Date objects anymore...

What do you think, can this solve the problem?
Instead of checking if input isObject([object Object]), directly check if is [object Date].

### CODE REVIEW

**Comment by adrai** [comment]
The relevant part is in format.js:

``` javascript
       if (isString(input)) {
         return input.match(/^\d{4}-(?:0[0-9]{1}|1[0-2]{1})-[0-9]{2}$/);
       }
-      if (isObject(input)) {
-        return Object.prototype.toString.call(input) === '[object Date]';
-      }
-      return false;
+      return Object.prototype.toString.call(input) === '[object Date]';
     },
```

Can this be fixed?

**Comment by adrai** [comment]
@Baggz Can you give some feedback?

**Comment by melon** [comment]
@adrai I came across the same problem too!Obviously, it's a mistake.

**Comment by Baggz** [comment]
> Can this be fixed?

@adrai Sure, will do.

**Comment by adrai** [comment]
Would be really nice so I can delete my fork... :-)

**Comment by adrai** [comment]
@Baggz what do you plan to do with this issue?

**Comment by adrai** [comment]
@Baggz When you find a couple of minutes, please try to give your opinion to this...

**Comment by tu1ly** [comment]
https://github.com/Baggz/Amanda/commit/0e5ac6fa0e94274854b87511cf309e0e5ece7c10   - sorry it took so long :/

**Pull request closed without merging**
